# Generated by Django 6.1 on 2026-08-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('nivel', models.CharField(choices=[('Pr', 'Principiante'), ('In', 'Intermedio'), ('Av', 'Avanzado')], default='Pr', max_length=2)),
                ('num_lecciones', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
        ),
    ]
