# Generated by Django 6.1.1 on 2026-09-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_curso_descripcion_alter_curso_nivel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='num_lecciones',
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('duracion', models.IntegerField()),
                ('nivel', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=9)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='gestor.curso')),
            ],
        ),
    ]
