# Generated by Django 6.1.1 on 2026-09-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_remove_curso_num_lecciones_leccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leccion',
            old_name='nivel',
            new_name='estado',
        ),
    ]
