# Generated by Django 6.1.1 on 2026-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_rename_nivel_leccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
    ]
